### ISSUE TITLE
Adding ormconfig to project changes build output in dist directory

### ISSUE THREAD

**Issue by conspireagency** [nestjs/typeorm#1139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After adding an ormconfig to a project it changes the build output in the dist directory.  

Prior the project would output directly to the root of the dist folder.  

Now when build occurs the ormconfig related files live in the root of the dist folder while the rest of the build is placed in the src subfolder of dist.

### Minimum reproduction code

https://docs.nestjs.com/techniques/database

### Steps to reproduce

Add ormconfig to a project and run a nest build.  Compare output before + after.

### Expected behavior

Ideally the build output wouldn't change or could be defined so that build output is the same.  We've experienced that this breaks deployments.

### Package version

7.1.0

### NestJS version

7.0.0

### Node.js version

12

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
THis will be true if you use `ormconfig.ts`. If it is a `js` file, the `dist` structure will not change (assuming you never import the js file). This is how Typescript works to ensure the `dist` directory has the same file import paths

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
