### ISSUE TITLE
Cannot manually set up charset in mysql

### ISSUE THREAD

**Issue by yeungon** [nestjs/typeorm#1144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi Nestjsters!

Not sure what is wrong with my configuration but it seems that I cannot set the charset for a Mysql database on purpose. Some of the discussions I found about that, listed as below:

https://orkhan.gitbook.io/typeorm/docs/connection-options#mysql-mariadb-connection-options      https://github.com/typeorm/typeorm/issues/390#issuecomment-292452066

Please take a look at the gist link which is my current configuration. In short, I want to set the charset as `charset: 'utf8mb4',` but after @Entity("table") was designed and the respective database was then generated, the charset was not set as I expected.

### Minimum reproduction code

https://gist.github.com/yeungon/14cc81568c6a00398ee6027300a7d356

### Expected behavior

the charset checked via phpadmin/adminer should be the same as defined by the configuration in the appmodule.

### Package version

8.0

### NestJS version

8.0

### Node.js version

16.13.1-alpine

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Thanks for your time. It is my pleasure to work with Nestjs.

Cheer

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
