### ISSUE TITLE
Support for typeorm 0.3.0

### ISSUE THREAD

**Issue by Hirsw0w** [nestjs/typeorm#1213]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Connection methods are now deprecated and we need a way to export the datasource

### Describe the solution you'd like

Upgrading to 0.3.0 and fixing the deprecated code

### Teachability, documentation, adoption, migration strategy

https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md

### What is the motivation / use case for changing the behavior?

new version of typeorm

**Comment by jmcdo29** [comment]
[Let's track this here](https://github.com/nestjs/typeorm/pull/384)

**Comment by felix-gohla** [comment]
Is the linked pull request also the place to track things like the deprecated `Connection` class or the deprecated `name` property of `Connection` / `DataSource`? Just wondered because of the title of the PR.

**Comment by kamilmysliwiec** [comment]
@felix-gohla we'll create a new, separate PR to make this library compatible with TypeORM 0.3.0. I'll keep everyone posted!

**Comment by micalevisk** [comment]
@jmcdo29 Can we reopen & pin & lock this Issue? so people could subscribe to it if they want to know about the development of that next version. I'm proposing this because we can't pin pull requests

**Comment by jmcdo29** [comment]
I believe we'll need @kamilmysliwiec for pinning the issue, so I'll leave it up to him
