### ISSUE TITLE
add support for typeorm 3

### ISSUE THREAD

**Issue by TrejGun** [nestjs/typeorm#1229]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

no

### Describe the solution you'd like

release new major version of @nestjs/typeorm which supports typeorm 3

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

this is the future of typeorm

**Comment by micalevisk** [comment]
duplicate #1213

**Comment by TrejGun** [comment]
ok
