### ISSUE TITLE
The deprecated/alias ConnectionOptions type is no longer exported from typeorm

### ISSUE THREAD

**Issue by eduardoconti** [nestjs/typeorm#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

'typeorm' >= 3.0 has no exported member named 'ConnectionOptions'
![image](https://user-images.githubusercontent.com/73971707/161462252-1f5e91e8-3066-419d-ba4b-e9b4d5fc8cff.png)

### Minimum reproduction code

no

### Steps to reproduce

try use typeorm >= 0.3.0 with nestJs

### Expected behavior

The ConnectionOptions type is @deprecated as of [v0.3.0](https://github.com/typeorm/typeorm/pull/8616 (2022-03-17).) The Connection type was also marked as @deprecated in this same version, but both types still have 'alias' types for backwards compatibility's sake. This is accomplished by declaring that ConnectionOptions extends DataSourceOptions and Connection extends DataSource, respectively:

### Package version

8.0.3

### NestJS version

8.4.1

### Node.js version

15.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
![image](https://user-images.githubusercontent.com/28268680/161462842-3764ea53-52ae-4678-8a19-f72c15ba4f9f.png)

We are working on 0.3.0 support. Please see [this PR](https://github.com/nestjs/typeorm/pull/1233) to keep up with progress
