### ISSUE TITLE
when will the typeorm dependency updated ,the latest version of typeorm has lot improvements(0.3.6) but nestjs/typeorm still uses has a very old version

### ISSUE THREAD

**Issue by yaswanthpflegia** [nestjs/typeorm#1255]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

features like setRelationLoadStrategy in typeorm 

### Describe the solution you'd like

For queries returning big amount of data, we recommend to use query strategy,
because it can be a more performant approach to query relations.

added new findOneBy, findOneByOrFail, findBy, countBy, findAndCountBy methods to BaseEntity, EntityManager and Repository:
const users = await userRepository.findBy({
    name: "Michael"
})
Overall find* and count* method signatures where changed, read the "breaking changes" section for more info.

new select type signature in FindOptions (used in find* methods):
userRepository.find({
    select: {
        id: true,
        firstName: true,
        lastName: true,
    }
})

### Teachability, documentation, adoption, migration strategy

For queries returning big amount of data, we recommend to use query strategy,
because it can be a more performant approach to query relations.

added new findOneBy, findOneByOrFail, findBy, countBy, findAndCountBy methods to BaseEntity, EntityManager and Repository:
const users = await userRepository.findBy({
    name: "Michael"
})
Overall find* and count* method signatures where changed, read the "breaking changes" section for more info.

new select type signature in FindOptions (used in find* methods):
userRepository.find({
    select: {
        id: true,
        firstName: true,
        lastName: true,
    }
})

### What is the motivation / use case for changing the behavior?

For queries returning big amount of data, we recommend to use query strategy,
because it can be a more performant approach to query relations.

added new findOneBy, findOneByOrFail, findBy, countBy, findAndCountBy methods to BaseEntity, EntityManager and Repository:
const users = await userRepository.findBy({
    name: "Michael"
})
Overall find* and count* method signatures where changed, read the "breaking changes" section for more info.

new select type signature in FindOptions (used in find* methods):
userRepository.find({
    select: {
        id: true,
        firstName: true,
        lastName: true,
    }
})

**Comment by jmcdo29** [comment]
[Following this comment from the upgrade PR](https://github.com/nestjs/typeorm/pull/1233#issuecomment-1091639776) you can use `@nestjs/typeorm@next` to use `typeorm@^0.3.0`
