### ISSUE TITLE
0.3.* typeorm version compability

### ISSUE THREAD

**Issue by elderapo** [nestjs/typeorm#1258]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In `typeorm@0.3.*` `Connection` has been replaced with `DataSource` and deprecated. `@nestjs/typeorm` is not aware of `DataSource` and cannot inject it into services.

### Describe the solution you'd like

To work with `typeorm@0.3.*`.

### Teachability, documentation, adoption, migration strategy

https://github.com/typeorm/typeorm/releases/tag/0.3.0

### What is the motivation / use case for changing the behavior?

.

**Comment by jmcdo29** [comment]
[Did you even look at our pull requests before making a new issue?](https://github.com/nestjs/typeorm/pull/1233#issuecomment-1091639776) [Or read our documentation?](https://docs.nestjs.com/techniques/database#typeorm-integration)
