### ISSUE TITLE
 Unable to connect to the database.

### ISSUE THREAD

**Issue by dkusliy** [nestjs/typeorm#1341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "aurora-mysql", "aurora-postgres", "better-sqlite3", "capacitor", "cockroachdb", "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "nativescript", "oracle", "postgres", "react-native", "sap", "sqlite", "sqljs", "spanner".

Config set in ormconfig.js

[Nest] 30  - 07/14/2022, 8:40:02 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
app_1        | MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "aurora-mysql", "aurora-postgres", "better-sqlite3", "capacitor", "cockroachdb", "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "nativescript", "oracle", "postgres", "react-native", "sap", "sqlite", "sqljs", "spanner".
app_1        |     at DriverFactory.create (/usr/src/app/node_modules/typeorm/driver/DriverFactory.js:72:23)
app_1        |     at new DataSource (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:49:59)
app_1        |     at createTypeormDataSource (/usr/src/app/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:172:23)
app_1        |     at Function.<anonymous> (/usr/src/app/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:176:46)
app_1        |     at Generator.next (<anonymous>)
app_1        |     at /usr/src/app/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:20:71
app_1        |     at new Promise (<anonymous>)
app_1        |     at __awaiter (/usr/src/app/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:16:12)
app_1        |     at /usr/src/app/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:174:76
app_1        |     at Observable._subscribe (/usr/src/app/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:31)

### Minimum reproduction code

https://gist.github.com/dkusliy/745634b9d142230efdc9824fec8e3461

### Expected behavior

connect to postgres

### Package version

@nestjs/typeorm: 9.0.0 

### Node.js version

14.15

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
Please provide a minimum reproduction **app**.

[Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required).

I don't think this is related to nestjs, tho
