### ISSUE TITLE
TypeORM 0.3 CLI Wrapper

### ISSUE THREAD

**Issue by MarZab** [nestjs/typeorm#1357]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

While using nestjs-typeorm, the convention is to load entities in modules eq `imports: [TypeOrmModule.forFeature([User])],` or/and using `autoLoadEntities`.

To use typeorm-cli 0.3, one has to
 - supply a path to the dataSource that exports the entities so one needs to keep a different list of entities to export, negating the benefit of `forFeature` and `autoLoadEntities`, using loading entities from glob patterns is still available but deprecated
 - supply the full path to the migration - while the old cli allowed for a preset path, this was deprecated

Along with using `tsconfig-paths` and setting the environment, the command I need to use looks like this.

`STAGE=local yarn node -r tsconfig-paths/register $(yarn bin typeorm-ts-node-commonjs) migration:generate src/modules/flower/database/migrations/init -d ./src/modules/app/app.data-source.ts`

I believe this syntax is, if anything, not efficient. I have prepared a yargs tool that I use to prepare these commands [here](https://gist.github.com/MarZab/3cb9eea8481fc84bbfc690c4953a21a0).
 

### Describe the solution you'd like

I propose a cli tool bundled with nestjs-typeorm that wraps typeorm-cli to make the commands leaner and re-use nestjs-typeorm entity loading.

Needed configuration would include the mirations path, ie `database/entities/` or `modules/${module-name}/database/entities`. 

I'm not sure what the nestjs approved way of making a cli like this would be - would it be to extend the nest cli?

### Teachability, documentation, adoption, migration strategy

```
yarn typeorm:cli migration:generate -m [module-name] [migration-name]
yarn typeorm:cli migration:run
```

### What is the motivation / use case for changing the behavior?

Using the cli tool should be easy and intuitive, nestjs-typeorm should re-use entities to prevent issues.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
