### ISSUE TITLE
Support for providing connection name while defining repository.

### ISSUE THREAD

**Issue by devops-versai** [nestjs/typeorm#1375]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

We have been using repository pattern and it's been pretty good but as we are shifting to use multiple databases in the code we noticed that we have to use @InjectRepository structure which will make it impossible to use the repo structure.

### Describe the solution you'd like

Adding support to define the connection name while defining the repository so it can be easily integrated as before

### Teachability, documentation, adoption, migration strategy

NA

### What is the motivation / use case for changing the behavior?

Easy addition of multiple db support and continued repository based arch of code

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
