### ISSUE TITLE
Error: connect EACCES xxx.xxx.xxx.xxx:3306 - Local (undefined:undefined)

### ISSUE THREAD

**Issue by Mahoo12138** [nestjs/typeorm#1394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Can't connect the mysql database in production environment

### Minimum reproduction code

https://github.com/nestjs/typeorm/

### Expected behavior

It 's OK in the development env using the command ` nest start --watch`, and get this error after building using the `node dist/main`
After that, this is  remote database, it has been set opening.

### Package version

9.0.1

### NestJS version

8.0.0

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
This would be a problem with how you're connecting to your database, not something with the framework itself. Please use our [Discord])https://discord.gg/nestjs) for support
