### ISSUE TITLE
Custom repository Error

### ISSUE THREAD

**Issue by hellraisercenobit** [nestjs/typeorm#14]
With typeorm we can use custom repository to override default one to add extra methods.

For example:
```
@Component()
@EntityRepository(Jwt)
export class JwtRepository extends Repository<Jwt> {

}
```

After we juste have to inject it inside controller/model/service etc... like this:
```
  constructor(
    @OrmRepository('connectionName')
    private readonly jwtRepository: jwtRepository,
```

But only InjectRepository decorator is available on nestjs, so if we try to inject repo into a service:
```
@Component()
export class MyService {
  constructor(
    @InjectRepository(Jwt)
    private readonly jwtRepository: JwtRepository,
```

We got this error for any repo function:
```
Cannot read property 'findOne' of undefined
    at JwtRepository.Repository.findOne
```

How it is possible to use custom repo?

**Comment by BrunnerLivio** [comment]
After hours of Googling, I finally found a workaround. The solution is still pretty elegant in my opinion, but this should actually be supported out of the box.

The workaround I use, is using a provider.

My image.repository.ts
```TypeScript

/**
 * The image repository represents the
 * interface between the appliaction image entity
 * and the database.
 */
@EntityRepository(Image)
export class ImageRepository extends Repository<Image> {
    /**
     * Finds all images and applies the given pagination
     * options
     * @param pagination The pagination options
     */
    async findAll(pagination: PaginationOptionsDto): Promise<[Image[], number]> {
        // Get Images with the pagination options applied
        // from the database.
        return await this
            .createQueryBuilder('image')
            .offset(pagination.offset)
            .limit(pagination.limit)
            .getManyAndCount();
    }
}

export const ImageRepositoryProvider = {
    provide: 'ImageRepository',
    useFactory: (connection: Connection) => connection.getCustomRepository(ImageRepository),
    inject: [Connection]
};
```

In the module, simply inject the provider.

E.g.
image.module.ts:
```TypeScript
import { ImageRepositoryProvider } from './image.repository';

@Module({
  imports: [
    TypeOrmModule.forFeature([Image])
  ],
  controllers: [ImageController],
  components: [
    ImageRepositoryProvider
  ],
})
/**
 * The Image module, which bundles all
 * operational or processable image related
 * modules, controllers and components
 */
export class ImageModule { }

```

Now using @Inject('ImageRepository'), you can inject it into your services etc.

**Comment by hellraisercenobit** [comment]
oh yeah :) thx a lot @BrunnerLivio ! i'll try it soon to give you my feedback.

**Comment by hellraisercenobit** [comment]
@BrunnerLivio 
Working like a charm!
Thx man!

**Comment by kamilmysliwiec** [comment]
This feature will be available in the nearest release (here's a pull request https://github.com/nestjs/typeorm/pull/18)

**Comment by shusson** [comment]
@kamilmysliwiec [this](https://github.com/typeorm/typeorm/blob/master/docs/custom-repository.md#using-custom-repositories-in-transactions-or-why-custom-repositories-cannot-be-services) indicates that we shouldn't be creating services from custom repositories, especially if you want to use transactions. Thoughts?

**Comment by basvdijk** [comment]
@kamilmysliwiec What would be the correct use of this feature? Do you have an example?

**Comment by theduke** [comment]
@kamilmysliwiec yeah some documentation would be appreciated

**Comment by regniblod** [comment]
@kamilmysliwiec +1 for documentation.
