### ISSUE TITLE
Add custom repository support

### ISSUE THREAD

**Issue by ruscon** [nestjs/typeorm#1422]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Feature request related to breaking changes between `typeorm@^0.2` and `typeorm@^0.3` versions

### Describe the solution you'd like

A fully working solution is described [here](https://github.com/nestjs/typeorm/issues/1302#issuecomment-1153148826)

### Teachability, documentation, adoption, migration strategy

In order not to introduce breaking changes, we can add a separate method `TypeOrmModule.forCustomRepositoryFeature` which will do what the `TypeOrmModule.forFeature` method does now (maybe just call it) and at the same time logic to support custom repositories.

### What is the motivation / use case for changing the behavior?

Ease of use and extensibility of the repository pattern with additional method definitions.

**Comment by micalevisk** [comment]
[custom repositories](https://typeorm.io/custom-repository) are still supported already, but not the `AbstractRepository` one because it was deprecated in v0.3

As `Repository` is defined on `typeorm` package (not `@nestjs/typeorm`) we would have to move their code to here (or something like that) in order to implement what you're requesting? :thinking: not sure if I follow

**Comment by ruscon** [comment]
@micalevisk 
> Or maybe just those pieces like described in that gist
I see no reason to copy all logic from `typeorm@0.2` around the custom repository.
The solution described in the gist is sufficient.

**Comment by kamilmysliwiec** [comment]
IMO this approach https://gist.github.com/anchan828/9e569f076e7bc18daf21c652f7c3d012?permalink_comment_id=4319458#gistcomment-4319458 is significantly simpler. 

Anyways, there are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
