### ISSUE TITLE
Supporting custom repositories without extends

### ISSUE THREAD

**Issue by jeiea** [nestjs/typeorm#143]
## I'm submitting a...
- [x] Feature request

## Current behavior
```
Error: Nest can't resolve dependencies of the UserService (?). Please make sure that the argument at index [0] is available in the UserModule context.
    at Injector.lookupComponentInExports (@nestjs\core\injector\injector.js:180:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at Injector.resolveComponentInstance (@nestjs\core\injector\injector.js:143:33)
    at resolveParam (@nestjs\core\injector\injector.js:96:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (@nestjs\core\injector\injector.js:112:27)
    at Injector.loadInstance (@nestjs\core\injector\injector.js:78:9)
    at Injector.loadProvider (@nestjs\core\injector\injector.js:35:9)
    at async Promise.all (index 2)
    at InstanceLoader.createInstancesOfProviders (@nestjs\core\injector\instance-loader.js:41:9)
```

## Expected behavior
No error message.

## Minimal reproduction of the problem with instructions
```
// UserRepository.ts
import { EntityRepository, Repository, EntityManager } from "typeorm";

@Entity()
class User {}

@EntityRepository(User)
export class UserRepository {
    private readonly repository: Repository<User>;

    constructor(manager: EntityManager) {
        this.repository = manager.getRepository(User);
    }
}
```
```
// user.module.ts
import { TypeOrmModule } from '@nestjs/typeorm';
import { UserRepository } from './UserRepository';

@Module({
    imports: [
        TypeOrmModule.forFeature([
            UserRepository
        ]),
    ]
})
```

## What is the motivation / use case for changing the behavior?
I tried using a [custom repository without extends](https://typeorm.io/#/custom-repository/custom-repository-without-extends). It is a documented approach and can improve safety by reducing functionality surface in my thought.

Can it be supported? Currently it seems only class inheritance is checked.

## Environment
Nest version: 6.3.1
Node version: 12.3.1
Platform:  Windows

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by jeiea** [comment]
@kamilmysliwiec I just uploaded [a example repository](https://github.com/jeiea/typeorm-issue).

**Comment by asishap007** [comment]
@jeiea 
Have to solved this issue ?

**Comment by jeiea** [comment]
@asishap007 If you meant what is the priority of this issue, it may be low.

**Comment by redlock** [comment]
It used to work in version 5.2.2 but now it is giving this error.

**Comment by asishap007** [comment]
@redlock 
Thanks. So in 5.2.2 typeorm version will work custom repositories without extends in nestjs ?
Is there any plan to fix this issue in upcoming version ?

**Comment by kamilmysliwiec** [comment]
You can just create a service (with "Repository" suffix in the name) that injects a repository and thus, reduce the functionality surface. This feature isn't needed with NestJS
