### ISSUE TITLE
Add a test with getRepositoryToken

### ISSUE THREAD

**Issue by OSA413** [nestjs/typeorm#1435]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

This repository features many e2e tests. Unfortunately none of them provide an example of repository usage inside the test itself. That would be useful for others to quickly find that it's possible to get repositories from the module for tests.

### Describe the solution you'd like

Apparently there are two tests in the main repository that features such functionality: 
https://github.com/nestjs/nest/blob/master/sample/05-sql-typeorm/src/users/users.service.spec.ts#L45
https://github.com/nestjs/nest/blob/master/sample/13-mongo-typeorm/src/photo/photo.service.spec.ts#L40

Maybe it's possible to copy the tests to this repository since it was the first place that I tried to search for such thing, then I found it there.

### Teachability, documentation, adoption, migration strategy

This will make such information less hidden from the users.

### What is the motivation / use case for changing the behavior?

_Described it above_

**Comment by micalevisk** [comment]
> This will make such information less hidden from the users.

you know that the `getRepositoryToken` is already [in the docs site](https://docs.nestjs.com/techniques/database#testing), right?

but yeah, we could use that feature in this repo for those who cannot access the docs site nor the https://github.com/nestjs/docs.nestjs.com somehow
