### ISSUE TITLE
A functionality that enables `forRootAsync()` to initialize database connection in the bootsr

### ISSUE THREAD

**Issue by 1000ch** [nestjs/typeorm#1462]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

`forRootAsync()` doesn't ensure DB connection is established during `nest` bootstrapping because the DB connection will be postponed until it gets the first request if a scope of a logger is `Scope.REQUEST`.

### Describe the solution you'd like

I would like to ensure the situation, DB connection is established during the `nest` bootstrapping AND the logger is able to capture `x-request-id`s by having an additional option for `forRootAsync()` (but please let me know if we already have an existing solution for this).

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

Described above.

**Comment by micalevisk** [comment]
actually, `TypeOrm` module creates a provider that depends on a database connection as you can see below:

https://github.com/nestjs/typeorm/blob/9ff75c597822b235ede9e57552087ca8dbf28e91/lib/typeorm-core.module.ts#L85

thus your app won't be created until you got some connection established (unless you're using the lazy-loading feature)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
