### ISSUE TITLE
'InjectConnection' is deprecated.

### ISSUE THREAD

**Issue by siamahnaf198** [nestjs/typeorm#1473]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the regression

Hello, I try to use typeorm event subscriber by this way-

```
import { Injectable } from '@nestjs/common';
import { InjectConnection, InjectRepository } from '@nestjs/typeorm';
import { Connection, EntitySubscriberInterface, InsertEvent, Repository } from 'typeorm';
import { User } from '../model/user.entity';

@Injectable()
export class PostSubscriber implements EntitySubscriberInterface {

    constructor(
        @InjectConnection() readonly connection: Connection,
        // Inject your repository here
        @InjectRepository(User) private readonly postRepository: Repository<User>,
    ) {
        connection.subscribers.push(this);
    }

    listenTo() {
        return User;
    }

    beforeInsert(event: InsertEvent<User>) {
        console.log("Hello")
    };
}
```

But Here I found this-
'InjectConnection' is deprecated.
'Connection' is deprecated.

If it is deprecated, how other possible way to use typeorm event subscriber?

![image](https://user-images.githubusercontent.com/78312010/209360059-6495d4e5-3d05-4811-8d50-c2fae9518edd.png)

### Minimum reproduction code

```ts

```

### Expected behavior

No idea

**Comment by micalevisk** [comment]
use `InjectDataSource` and `DataSource` instead.

You could open a PR to make that clear here:

https://github.com/nestjs/typeorm/blob/ea264dc44bd6f1e4f8b53e9bfae7631691afe9c8/lib/common/typeorm.decorators.ts#L22-L23

```
/** @deprecated Use InjectDataSource instead. */
```
