### ISSUE TITLE
"name" parameter is deprecated by typeorm documentation, but is required while registering multiple databases in nestjs project. 

### ISSUE THREAD

**Issue by Seberyak** [nestjs/typeorm#1512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

deprecated parameter "name" is required for identifying datasources in project 

### Minimum reproduction code

https://github.com

### Expected behavior

It shouldn't be deprecated, or new identifier should be added

### Package version

9.0.1

### NestJS version

9.0.11

### Node.js version

16.16.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
`@nestjs/typeorm` `name` !== `typeorm` `name`. We still require folks to provide the name parameter so we can distinguish different data sources.

**Comment by Seberyak** [comment]
![image](https://user-images.githubusercontent.com/43892697/215763190-d5c7f73f-d3d1-45e2-8930-2c221139670d.png)
@kamilmysliwiec  what about that?

**Comment by Nosfistis** [comment]
The parameter is still marked as deprecated. #1557 was not merged!

**Comment by Labham-Jain** [comment]
looks like it's still not merged, I was looking around for alternative for this from past 2 days but eventually I went with using it and now I found this thread... 🙁
