### ISSUE TITLE
.getOne() does not return any result with queryBuilder.select()

### ISSUE THREAD

**Issue by natikos** [nestjs/typeorm#1516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```js
const item = await this.documentRepository
      .createQueryBuilder('item')
      .innerJoin('item.parent', 'parent')
      .where('item.id = :itemId', { itemId })
      .select(['item.id', 'parent.id'])
      .getOne()
```

This builds correct raw SQL query: 
```SQL
query : 
SELECT 
  `item`.`id` AS `item_id`, 
  `parent`.`id` AS `parent_id` 
FROM 
  `item` `item` 
  INNER JOIN `parent` `parent` ON `parent`.`id` = `item`.`parentId` 
WHERE 
  (`item`.`id` = ?) -- PARAMETERS: [1]
```
When I run the query in my SQL client I got result, but when I run queryBuilder with `getOne()` it returns nothing. `getRawOne()` works as expected.

### Minimum reproduction code

https://github.com

### Expected behavior

Result must be returned with `getOne()`.

### Package version

8.0.2

### NestJS version

8.0.0

### Node.js version

16.19.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
This is not related wit Nest but Typeorm as `@nestjs/typeorm` change nothing on `typeorm`'s behavior.

Please report to them instead.  
`npm docs typeorm`

**Comment by micalevisk** [comment]
tip: you can see the query generated by using `.getQuery()`

https://typeorm.io
