### ISSUE TITLE
add nestjs v9 as a peer dependency of `@nestjs/typeorm`  v8 

### ISSUE THREAD

**Issue by micalevisk** [nestjs/typeorm#1551]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to use nestjs v9 (`@nestjs/core`, and others packages) but I cannot upgrade `@nestjs/typeorm` to v9 because I need to still use typeorm v0.2

AFIAK I can use `@nestjs/typeorm@8.0.4` with `@nestjs/core@9` just fine. Also, the latest version of `@nestjs/typeorm` can be used with nestjs v8.

https://github.com/nestjs/typeorm/blob/7e6852d89fc95f298849a744ded0f7ac94ce8df7/package.json#L55-L57

### Describe the solution you'd like

Add `@nestjs/core^9.0.0` and `@nestjs/common@^9.0.0` in the peer deps list of `@nestjs/typeorm@8.0.4` (which is the latest version that works for `typeorm@^0.2`) and publish it under v8.0.5

https://github.com/nestjs/typeorm/blob/f612777da58ba048656299394c2d9f4a0385d104/package.json#L54-L56

### Teachability, documentation, adoption, migration strategy

N/A

### What is the motivation / use case for changing the behavior?

The migration to the latest version of `@nestjs/typeorm` can be more smooth and won't block the upgrade of others `@nestjs/` packages.

Also, I believe that `@nestjs/typeorm` doesn't need to be strictly aligned with the version of `@nestjs/core` being used since `@nestjs/typeorm@9` supports `@nestjs/core@8`

My main motivation here was to be able to use `@nestjs/devtools-integration` to inspect circular dependencies issues and as of now I can't upgrade `@nestjs/core`  due to the need of use `@nestjs/typeorm@8.0.4` which has such peer dep.

**Comment by kamilmysliwiec** [comment]
Just released 8.0.5, good call!
