### ISSUE TITLE
TypeOrmModule.forRoot() report errors： ConnectionNotFoundError: Connection "default" was not found.

### ISSUE THREAD

**Issue by AliSnowaroma** [nestjs/typeorm#1632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

``### Using it like this, I got an error at dev 

### error:
**ConnectionNotFoundError: Connection "default" was not found.**

### code：
```js
import { Module, forwardRef } from '@nestjs/common';
import { AppController } from './app.controller';
import IndexModule from './controllers/index.module'
import { AppService } from './app.service';
import { TypeOrmModule } from '@nestjs/typeorm';
import config from '@/config'
const { host, port, username, password, database } = config.mysqlConfig

@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'mysql',
      host,
      port,
      username,
      password,
      database,
      synchronize: true,
      logging: process.env.API_ENV !== 'real',
      autoLoadEntities: true
    }),
    forwardRef(() => IndexModule)
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
using getConnectionOptions Unable to obtain configuration，but get errors
```js
import { getConnectionOptions } from 'typeorm'
...
const options = getConnectionOptions
```

I have tried many things, but I haven't found a solution yet

### Minimum reproduction code

https://github.com/nestjs/typeorm/issues/new?assignees=&labels=needs+triage%2Cbug&template=Bug_report.yml

### Expected behavior

Normal use of getConnection

### Package version

9.0.1

### NestJS version

9.0.0

### Node.js version

v16.16.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please use our [Discord](https://discord.gg/nestjs) channel (Support). We are using GitHub to track Bug Reports, Feature Requests, and Regressions.

**Comment by eldhoseelias** [comment]
Any solution to this issue ?

**Comment by AliSnowaroma** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，谢谢

**Comment by jmcdo29** [comment]
Y'know, if someone says to go ask this where support is officially given, and then closes the issue, you'd think others would realize that that's where to go to find a solution/some extra help
