### ISSUE TITLE
Named connection and multiple Connection

### ISSUE THREAD

**Issue by hellraisercenobit** [nestjs/typeorm#17]
With typeorm and typedi we can specify a connection name for a repository like this:

```
import { Service } from 'typedi';
import { OrmRepository } from 'typeorm-typedi-extensions';
import { ExampleRepository } from './example.repository';

@Service()
export class ExampleModel {
  constructor(
    @OrmRepository('myconnectionname')
    private readonly repository: ExampleRepository) {
  }
```

To manage multiple connections, we just have to use createConnections method instead of createConnection (as array of connection).
Why TypeOrmModule.forRoot method do not support Array?
I know, it will be implemented but if someone know when, it's welcome.
Is there a way to set connection name instead of default one?

**Comment by kamilmysliwiec** [comment]
This feature will be available in the nearest release (here's a pull request https://github.com/nestjs/typeorm/pull/18)
