### ISSUE TITLE
Option to not initialize DataSource in createDataSourceFactory

### ISSUE THREAD

**Issue by Junikorn** [nestjs/typeorm#1762]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have to create nestjs app using `@nestjs/typeorm` without connecting to database during app creation

### Describe the solution you'd like

An option in `TypeOrmModuleOptions` to leave `DataSource.initialize` to be run manually

### Teachability, documentation, adoption, migration strategy

No migration startegy necessary, this feature should be opt-in.

Simplified solution:
`/lib/typeorm-core.module.ts`
![screenshot](https://github.com/nestjs/typeorm/assets/1327040/31a36e08-e6a7-4491-ba25-cec269063924)

Same in line 241. Of course this would require interface changes and such. Option name up for discussion. Users should be made aware of usage consequences in the documentation.

### What is the motivation / use case for changing the behavior?

My current usecase is generating openapi documentation using `@nestjs/swagger` `DocumentBuilder` without a need to have a running database instance or mocking DataSource.
I also imagine that some applications might need to start even without connection to DB and report connection status using healthcheck endpoints instead of awaiting DB connection before exposing API (see [this StackOverflow question](https://stackoverflow.com/questions/74039650/start-nestjs-server-even-if-typeorm-module-cant-connect-to-one-of-its-databases))

**Comment by kamilmysliwiec** [comment]
Can you retrieve a repository of a non-initialized data source? This wasn't doable in previous versions of typeorm (with `createConnection`), hence the question

**Comment by Junikorn** [comment]
It seems you can
```
describe('DataSource', () => {
  it('should allow to retrieve repository before init', () => {
    const ds = new DataSource({
      type: 'postgres',
      host: 'localhost',
      port: 5434,
      username: 'postgres',
      password: 'password',
      database: 'postgres',
      entities: [Code],
    });
    const repository = ds.getRepository(Code);
    expect(repository).toEqual(expect.any(Repository));
  });
});
```

This test is passing for me

**Comment by kamilmysliwiec** [comment]
Sounds good. Would you like to create a PR for this issue then?

**Comment by Junikorn** [comment]
I think I can

**Comment by Junikorn** [comment]
I added [PR](https://github.com/nestjs/typeorm/pull/1766) for this issue

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/typeorm/pull/1766
