### ISSUE TITLE
Inject ConfigService into an Entity or Subscriber

### ISSUE THREAD

**Issue by asijoumi** [nestjs/typeorm#1848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,

I would like to know how can I inject the ConfigService into en Entity or Subscriber.

I tried with 2 different ways : 

```typescript
@Entity()
@Injectable()
export class User extends BaseEntity {
  constructor(private readonly configService: ConfigService) {
    super();
  }
}
```

But, configService is undefined.

The second way was to create a subscriber : 

```typescript
import { Inject } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { EntitySubscriberInterface, EventSubscriber } from 'typeorm';
import { User } from '../models/entities/user';

@EventSubscriber()
export class UserSubscriber implements EntitySubscriberInterface<User> {
  @Inject(ConfigService) private readonly configService: ConfigService;

  listenTo() {
    return User;
  }

  afterLoad(entity: User) {
    console.log(this.configService);
    console.log(`AFTER ENTITY LOADED: `, entity);
  }
}
````

But still the same problem.

Do you now how can I access to configService ?

PS : I need configService because some secrets are provided during the startup of application.

### Minimum reproduction code

No

### Expected behavior

Have configService

### Package version

10.0.1

### NestJS version

10.0.0

### Node.js version

20.5.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
those subscriber classes are managed by typeorm, not by nestjs. So there's no way to make them injectable AFIAK

maybe you could find a work around tho

**Comment by asijoumi** [comment]
The other way was to get the NestApplication instance (like we can do with Java Spring). Is that possible with Nest ?

**Comment by micalevisk** [comment]
I guess you could use the standalone mode https://docs.nestjs.com/standalone-applications

**Comment by asijoumi** [comment]
I actually have a Rest API working fine. 

The last solution (but I didn't really approved) is a static class with the necessary variables..
