### ISSUE TITLE
Nestjs warns about "TypeOrmModule" taking a long time to serialize

### ISSUE THREAD

**Issue by hfhchan-plb** [nestjs/typeorm#1873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

An error gets logged to the logs:
```
The module "TypeOrmModule" is taking 10.88ms to serialize, this may be caused by larger objects statically assigned to the module. More details: https://github.com/nestjs/nest/issues/12738
The module "TypeOrmModule" is taking 20.62ms to serialize, this may be caused by larger objects statically assigned to the module. More details: https://github.com/nestjs/nest/issues/12738
```

### Minimum reproduction code

```

@Module({
  imports: [
    TypeOrmModule.forRootAsync({
      inject: [],
      name: DBConnection.PG,
      useFactory: (): TypeOrmModuleOptions => ({
        name: DBConnection.PG,
        type: 'postgres',
        host: /* redacted */,
        port: /* redacted */,
        username: /* redacted */,
        password: /* redacted */,
        database: /* redacted */,
        entities:/* array of a ton of entities */,
        keepConnectionAlive: true,
        logger: /* redacted large object */
        ssl: {
          ca: /* huge string */,
        },
        applicationName: getApplicationName(),
        uuidExtension: 'pgcrypto',
        installExtensions: false,
      }),
    }),
  ],
})
export class EntityModule {}
```

### Expected behavior

No error

### Package version

10.0.1

### NestJS version

10.3.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
so what's the issue here?

**Comment by hfhchan-plb** [comment]
Sorry I've just updated the minimum reproduction code.

I'm using 10.3.0 which appears to be the latest version.

**Comment by micalevisk** [comment]
ok but what's the expected behavior?

that's just an warning message, not an error, right? You can see why it exists in the issue https://github.com/nestjs/nest/issues/12738

**Comment by hfhchan-plb** [comment]
I think the expected behavior would be that the TypeORM integration would avoid having a large amount of static data to be serialized?

I would like to find a way to remove that 30 ms extra time per cold start 🤔

**Comment by micalevisk** [comment]
I believe that this is a limitation that we cannot fix on the fw side yet

**Comment by hfhchan-plb** [comment]
This can probably be fixed by replacing the useValue with useFactory like the original issue

**Comment by micalevisk** [comment]
so please try it out changing the js code of your `node_modules`
