### ISSUE TITLE
Cannot read properties of undefined (reading 'retryAttempts') when start the app on production.

### ISSUE THREAD

**Issue by iyngaran** [nestjs/typeorm#1942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am using Typeform with NestJS. It works well in development. But when I run the app on production, It says the following error.

2024-03-22T07:18:20.480Z error:    Cannot read properties of undefined (reading 'retryAttempts')

I am using the following version.

```
"@casl/ability": "^6.5.0",
    "@faker-js/faker": "^8.3.1",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^3.0.1",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^10.2.0",
    "@nestjs/mapped-types": "^2.0.2",
    "@nestjs/passport": "^10.0.3",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/swagger": "^7.1.10",
    "@nestjs/typeorm": "^10.0.2",
    "@types/cookie-session": "^2.0.48",
    "bcrypt": "^5.1.1",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "cookie-session": "^2.0.0",
    "cross-env": "^7.0.3",
    "moment": "^2.30.1",
    "nest-winston": "^1.9.4",
    "nestjs-typeorm-paginate": "^4.0.4",
    "passport": "^0.7.0",
    "passport-jwt": "^4.0.1",
    "passport-local": "^1.0.0",
    "pg": "^8.11.3",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "sqlite3": "^5.1.6",
    "typeorm": "^0.3.20",
    "typeorm-extension": "^3.2.0",
    "uuid": "^9.0.1",
    "winston": "^3.11.0",
    "winston-daily-rotate-file": "^4.7.1"
```

![image](https://github.com/nestjs/typeorm/assets/13806950/3e5c5d5e-baa9-4c41-8f91-ac9143787fbd)

 

### Minimum reproduction code

https://github.com/iyngaran/billing-api

### Expected behavior

It should start the app as it works on development

### Package version

0.3.20

### NestJS version

9.0.0

### Node.js version

20.10.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
