### ISSUE TITLE
Add a way to check entities metadata on dev env 

### ISSUE THREAD

**Issue by jlefebvre1997** [nestjs/typeorm#2129]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Sometimes we forget to add a new entity to the relevant module's `TypeOrm.forFeature()` declaration. However, this does not fail at all locally or when building the project with `nest build`, but it fails once the app is deployed on production environment. So, often, we encounter a `Metadata not found` error once the app is deployed and not before. 

### Describe the solution you'd like

It would be nice to have a warning or even an error thrown in nest console or when running `nest build`, as it could prevent failing code to be deployed in production. Or even a specific command like `typeorm check-metadata`, idk 

### Teachability, documentation, adoption, migration strategy

Users could see quickly if metadatas are missing, before the code is deployed to production 

### What is the motivation / use case for changing the behavior?

Sometimes we forget to add a new entity to the relevant module's `TypeOrm.forFeature()` declaration. However, this does not fail at all locally or when building the project with `nest build`, but it fails once the app is deployed on production environment. So, often, we encounter a `Metadata not found` error once the app is deployed and not before.

**Comment by micalevisk** [comment]
are in using webpack? I wonder if this is related with https://github.com/nestjs/nest/issues/6397

**Comment by jlefebvre1997** [comment]
We do use webpack but I don't think this issue is related. It's not really an issue in itself, rather a lack of warning / error 

Fixing the issue is simple, we just have to add the entity declaration in the `forFeature` array, but NestJS doesn't throw any error locally

**Comment by micalevisk** [comment]
got you

and due to how that typeorm, if we have an entity like this:

```ts
@Entity()
export class Category {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    name: string

    @ManyToMany((type) => Question, (question) => question.categories)
    questions: Question[]
}
```

we need to ensure that both `Category` and `Question` typeorm entities are registered via ` .forFeature`

**Comment by jlefebvre1997** [comment]
That's exactly the kind of cases where we encounter this issue :sweat_smile: it's easy to forget adding an entity if it's not the "main" entity in the module

**Comment by jlefebvre1997** [comment]
Yes I guess that should do it, that would be nice actually, do you have any doc I can follow to do that by any chance ? :pray:

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
