### ISSUE TITLE
Stored procedure or typeorm transaction, which one is better ?

### ISSUE THREAD

**Issue by nandantal** [nestjs/typeorm#217]
We are using stored procedure on our project but want to move to typeorm transaction. What are the pros and cons ? 

Is there any examples on locking using typeorm ?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
