### ISSUE TITLE
BREAKING BUG: rxjs_1.from is not a function

### ISSUE THREAD

**Issue by ColonelBundy** [nestjs/typeorm#25]
Seems like you are trying to use ```import { from } from 'rxjs'``` [here](https://github.com/nestjs/typeorm/blob/4b802ec0368aa15cadb8e013059a7a75cab9f4f5/lib/typeorm-core.module.ts#L8)  which does not exist as a standalone export anymore, use instead ```Observable.from``` 

I came across this when updating to ```3.0``` and got the following error:
```
[ExceptionHandler] rxjs_1.from is not a function TypeError: rxjs_1.from is not a function at Function.<anonymous> (****\node_modules\@nestjs\typeorm\dist\typeorm-core.module.js:26:37)
```

**Comment by kamilmysliwiec** [comment]
You should install `rxjs@6.0.0`. As you can see here: https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/from.ts - `from()` is now a replacement for `fromPromise()`.

**Comment by MUHAMMEDBERKAY** [comment]
observable exit app.modules in imports

**Comment by nihadkv** [comment]
update "@nestjs/typeorm": "^7.1.5" in package.json and enter npm i and restart server
