### ISSUE TITLE
What if a database connection is failed , and i dont want other service broke

### ISSUE THREAD

**Issue by eret9616** [nestjs/typeorm#252]
Following the document , i init my project,
In my project, i have a router directory and a orm directory,
in router directory, i have two module : platform,tag 
(these module contains some controllers and services,
and provide some api such as   /tag/getTag  ,/platform/getInfo..)

<img width="204" alt="image" src="https://user-images.githubusercontent.com/12445095/71503916-277cc700-28b2-11ea-8231-c022c6778254.png">

<img width="197" alt="image" src="https://user-images.githubusercontent.com/12445095/71504140-39129e80-28b3-11ea-8725-0aebcbb4b58f.png">

i want to know  what if one database connection is failed ?
my whole service is broke,

e.g. the platformConnection is failed (because wrong password or something resulting can't connect the database), but the tagConnection (password) is okay.  then the whole service is broke and i cant request /tag/xxxx something, 

english is not my native language, helps ,thiankyou!

code below:

orm.module.ts:
```
import { Module } from '@nestjs/common';

const ormConfig = require(`./ormConfig/orm.${process.env.NODE_ENV}`);

@Module({
  imports: ormConfig
})
export class OrmModule {}
```

orm.development.ts:
```
import path = require('path');
import { TypeOrmModule, TypeOrmModuleOptions } from '@nestjs/typeorm';

const config: TypeOrmModuleOptions[] = [
  {
    type: 'mysql',
    name: 'userPortraitConnection',
    host: '192.xx8',
    port: 3306,
    username: 'root',
    password: 'uxxxx',
    database: 'zebxxxta',
    entities: [path.join(__dirname, '../entity/**/*.entity.js')],
    synchronize: true
  },
  {
    type: 'mysql',
    name: 'platformPSConnection',
    host: '19xxxx.171',
    port: 9030,
    username: 'root',
    password: 'root',
    database: 'pxxxbase',
    synchronize: true
  }
];

module.exports = config.map(item => TypeOrmModule.forRoot(item));
```

router.module.ts:
```
const RouterModules = [TagModule, PlatformModule];

@Module({
  imports: RouterModules,
  exports: RouterModules
})
export class Router {
```

tag.module.ts:
```
import { TagController } from './tag.controller';
import { TagService } from './services/tag.service';
import { TagCatalogService } from './services/tag-catalog.service';

// entities
import { CatalogModule } from '@entity/userPortraitConnection/Catalog/Catalog.module';

@Module({
  imports: [CatalogModule],
  providers: [TagService, TagCatalogService],
  controllers: [TagController]
})
export class TagModule {}
```

platform.module.ts:
```
import { Module } from '@nestjs/common';
import { PlatformController } from './platform.controller';
import { PlatformService } from './services/platform.service';

@Module({
  controllers: [PlatformController],
  providers: [PlatformService]
})
export class PlatformModule {}
```

**Comment by kamilmysliwiec** [comment]
In this case, you need a bit more flexibility over custom providers registered within the `@nestjs/typeorm` module. I'd recommend following this recipe: https://docs.nestjs.com/recipes/sql-typeorm which shows how to interact with TypeORM without `@nestjs/typeorm`.
