### ISSUE TITLE
[Bug] Breaking change published with 2.1.0

### ISSUE THREAD

**Issue by BRUNNEL6** [nestjs/typeorm#28]
Today I got really confused. I upgraded from 2.0.0 to 2.1.0. Since this is a minor change, it should be backwards-compatible [[source]](https://semver.org/), but my application broke:

```
Nest cannot export component / module that is not a part of the currently proccessed module (TypeOrmCoreModule). 
```

After some debugging I realized 2.1.0 already has upgraded to Nest 5.x.x [[proof]](#issuecomment-391282877), so that means it wont use the `components` but the `providers` property inside modules instead. Off course this will break my application, running Nest 4.x.x. 

Seems like publishing the version 2.1.0 was a mistake (should have been 3.0.0 instead). 

Mistakes happen, but I would have tracked down this error much quicker, if there were `git tags` (so I can `diff` different releases) and changelogs (so I can read it up, without looking through the source code).

I highly recommend to start those things.

**Comment by BRUNNEL6** [comment]
Proof:

```
/tmp/nestjs-typeorm-test is 📦  ⚠ via ⬢ v9.11.1 took 3s 
➜ npm i -s @nestjs/typeorm@2.1.0
+ @nestjs/typeorm@2.1.0
added 1 package from 1 contributor in 1.696s
[+] no known vulnerabilities found [1 packages audited]

/tmp/nestjs-typeorm-test is 📦  ⚠ via ⬢ v9.11.1 
➜ grep -rnw '/tmp/nestjs-typeorm-test/node_modules/@nestjs/typeorm' -e 'providers'
/tmp/nestjs-typeorm-test/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:38:            providers: [entityManagerProvider, connectionProvider],
/tmp/nestjs-typeorm-test/node_modules/@nestjs/typeorm/dist/typeorm.module.js:10:const typeorm_providers_1 = require("./typeorm.providers");
/tmp/nestjs-typeorm-test/node_modules/@nestjs/typeorm/dist/typeorm.module.js:14:        const providers = typeorm_providers_1.createTypeOrmProviders();
/tmp/nestjs-typeorm-test/node_modules/@nestjs/typeorm/dist/typeorm.module.js:21:        const providers = typeorm_providers_1.createTypeOrmProviders(entities, connection);
/tmp/nestjs-typeorm-test/node_modules/@nestjs/typeorm/dist/typeorm.module.js:24:            providers: providers,
/tmp/nestjs-typeorm-test/node_modules/@nestjs/typeorm/dist/typeorm.module.js:25:            exports: providers,

```

**Comment by kamilmysliwiec** [comment]
Inconsistency between main framework version and the additional modules make it really difficult to manage them correctly. In the (very) near future, I'm going to bump all packages to follow the same semantic versioning, thereby modules like `@nestjs/typeorm@v5.x.x` will match v5 and so on.

Anyway, thanks for reporting. Sorry that you have lost your time on this mistake.

**Comment by quezak** [comment]
Sorry to comment on an old issue :) I see the major versions are aligned now, but the minor releases are (quite understandaby) separate, hence I have a question -- is there a release history or a changelog for available somewhere for this package? I  can't find any here in the repo.

**Comment by PachowStudios** [comment]
A changelog would be really nice. Was surprised to not find one.
