### ISSUE TITLE
TypeOrmModule.forRoot - dynamic configuration

### ISSUE THREAD

**Issue by mgamperl** [nestjs/typeorm#29]
Hi,

I really like the simplicity of this module but there is one thing I can not understand:
How do you dynamically configure the database connection when using TypeOrmModule.forRoot
```ts
@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'mysql',
      host: 'localhost',
      port: 3306,
      ...      
    }),
  ],
})
```
I have a similar ConfigService like the one in https://docs.nestjs.com/techniques/configuration in my application and want to use that for the configuration of the database connection but its embarrassing, I can't find a solution on how to use this configuration in combination with TypeOrmModule.

I know I could do the creation of the connection in a custom provider following https://docs.nestjs.com/recipes/sql-typeorm but isn't there a simpler way which is as convenient as this module?

Thanks for help and thank you for the hard work you all are putting into nestjs I really love it!

**Comment by BrunnerLivio** [comment]
I used another approach in my project. I basically share the options through the AppModule:


main.ts
```TypeScript
const settings = dotenv.parse(fs.readFileSync(filePath));
const app = await NestFactory.create(AppModule.forRoot(settings));
...
```

app.module.ts
```TypeScript
export class AppModule {
    static forRoot(settings: APISettings): DynamicModule {
        return {
            module: AppModule,
            imports: [
                // This module has a ConfigurationService, which
                // does the same as described in the docs
                // but it does not read the env file.
                AppSettingsModule.forRoot(settings),
                DatabaseModule.forRoot(settings),
                ...
            ]
        };
    }
}
```


database.module.ts
```TypeScript
export function getOrmConfig(settings: IDatabaseSettings) {
     return {
            type: 'postgres',
            host: settings.host,
            port: settings.port,
            username: settings.username,
            password: settings.password,
            database: settings.database,
            entities,
            synchronize: true,
            logging: true,
        };
}

export class DatabaseModule {
  public static forRoot(settings?: IDatabaseSettings): DynamicModule {
    const ormConfig = getOrmConfig(settings);
    return {
      module: DatabaseModule,
      imports: [
        TypeOrmModule.forRoot(ormConfig)
      ],
      components: [
        DatabaseService,
      ],
      exports: [
        DatabaseService
      ]
    };
  }
}

```

I think it is a bad idea to read the configuration inside the service. For example; I have the use case, that my application should be useable and configureable by npm package (`npm i -s my-api`).  Lets assume my API is called `MyAPI`. Then the following code would not be possible, if the configuration is read by a nestjs service.

```TypeScript
import { MyAPI } from 'my-api';

// Bootstraps the NestJS configuration and calls await NestFactory.create(AppModule.forRoot(settings));
new MyAPI({ databaseHost: 'postgres', ... }).run();
```

Thats why I prefer my solution; its more dynamic and modular.

I hope you get what I mean :)

**Comment by mgamperl** [comment]
This is a really nice approach, I think I will try this for my use case. 
Thank you very much!

I'm closing this issue..

**Comment by AlexandreAWE** [comment]
I'm facing the same problem. 

@BrunnerLivio your approach is ok but I still prefer handle settings with  a service.

For now I didn't found a great a solution, I'm using ```process.env``` to retrieve settings in this particular case

**Comment by BrunnerLivio** [comment]
The [project I described in my upper comment is now opensourced](https://github.com/Roche/lxdhub).

You can checkout the [API](https://github.com/Roche/lxdhub/tree/master/packages/api) to see how I solved this issue.
The starting point would be [packages/api/bin/start-api.js](https://github.com/Roche/lxdhub/blob/master/packages/api/bin/start-api.js). Then you can go down further the rabbit hole in [packages/api/src/main.ts](https://github.com/Roche/lxdhub/blob/master/packages/api/src/main.ts) and [packages/api/src/app.module.ts](https://github.com/Roche/lxdhub/blob/master/packages/api/src/app.module.ts).

Good luck. Hit me up if you have any questions :)

**Comment by rsrsen** [comment]
@BrunnerLivio hi, I want to create 2 db connection, one is default, at the beginning, never changed. but second connection data, I want to set them from first connection's table data. I mean that one connection is always alive, second connection will be dynamic. 

Do you have any idea ? most of the samples, loads conf data at the beginning dynamically and then using same connection.  thank you
