### ISSUE TITLE
Not able to use 'greatest' postgres operator in order clause

### ISSUE THREAD

**Issue by Ajinkya1496** [nestjs/typeorm#302]
## I'm submitting a...

<pre><code>
[ ] Feature request.
</code></pre>

## Current behavior

What I am doing is running a raw sql query to the postgres database to fetch the results. Then I am passing that Ids from result to the pagination function. In that I am using order clause like this
`where:{
          id: In(idArray)
        },
        order: {col1: "DESC", col2: "DESC", col3: "DESC"}
`
With this I am getting a slightly wrong result.

## Expected behavior

When I tried the same thing with running plain queries in database, what I wanted was to do
`order by greatest(col1, col2, col3) desc`

But I am not able to find any equivalent operator in typeorm order clause.

## Minimal reproduction of the problem with instructions

1. Fire select query on any table having 3 columns with number type
2. Write order clause as `order by greatest(col1, col2, col3) desc`

Try to replicate the same thing with typeorm
`
this.repo.find({where:{
          id: In(idArray)
        },
        order: {col1: "DESC", col2: "DESC", col3:"DESC"})
`
## What is the motivation / use case for changing the behavior?

Is there any current functionality which does the same thing?
I need this feature asap.

## Environment

<pre><code>
Nest version: 6.5.0

 
For Tooling issues:
- Node version: 10.16.0  
- Platform: Linux  

Others:
Postgresql version: 10.11

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the typeorm repository https://github.com/typeorm/typeorm
