### ISSUE TITLE
How to test BeforeInsert with a mocked Repository ?

### ISSUE THREAD

**Issue by devniel** [nestjs/typeorm#336]
Hi, I'm trying to check that the method decorated with @BeforeInsert in my User entity is called, but with a mocked repository it's not working because it seems that @BeforeInsert is called when doing the actual insertion in the database, so maybe I need to mock one lower layer.

Is there a way to mock the typeorm feature that injects the repositories? I'm trying to test it without importing `TypeOrmModule.forRoot` so it can be tested without touching the database, maybe by mocking the global Connection.

```ts
const module: TestingModule = await Test.createTestingModule({
      controllers: [AuthResolver],
      imports: [
        /* TypeOrmModule.forRoot(getOrmConfig()) */
      ],
      providers: [
        AuthService,
        UsersService,
        {
          provide: getRepositoryToken(User),
          useFactory: repositoryMockFactory, 
        },
        {
          provide: getConnectionToken(),
          useValue: sandbox.createStubInstance(typeorm.Connection),
        },
      ],
    }).compile();
```

Because UsersService injects the repository, it's required in the providers, but with the mock it's losing the targeted interactions for the test, **is there a way to create a mock that includes the Typeorm connection ?** so the @BeforeInsert method in the User entity is called.

```ts
constructor(
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,
  ) {
```

Thanks.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by falyoun** [comment]
any solution ?

**Comment by devniel** [comment]
@falyoun I ended up creating a module to "solve" this, you can check it (I will update the deps soon) https://github.com/devniel/nestjs-typeorm-testing

**Comment by falyoun** [comment]
@devniel I already checked it, it does not solve the problem of spying on BeforeInsert, AfterInsert ...
