### ISSUE TITLE
forFeature Creating multiple connections causing DEAD_LOCK

### ISSUE THREAD

**Issue by ToonvanStrijp** [nestjs/typeorm#38]
## I'm submitting a...
<pre><code>
[ x ] Bug report
</code></pre>

## Current behavior

I'm defining my import as followed, for each entity that I want to use as a repository I define this in the forFeatures array.
```
imports: [
    TypeOrmModule.forRoot(),
    TypeOrmModule.forFeature([
      Answer,
      AnswerLog,
      Group,
      School,
      SchoolYear,
      Score,
      ScoreCalculated,
      Subject,
      User,
      ContentSuggestion,
      Todo,
      PlannedDay,
      WallItem,
    ]),
  ],
```
When I look at the log I saw that the TypeOrmModule is creating multiple connections for each repository. My question why?

Cause I think this is causing when I sometimes get a DEAD_LOCK error.

I don't know if this is a bug or not?

**Comment by kamilmysliwiec** [comment]
Nest has nothing to do with this ^ behavior. It is typeorm related thing.
