### ISSUE TITLE
Why should we call the module twice?

### ISSUE THREAD

**Issue by FriOne** [nestjs/typeorm#4]
I have one module in my app, with the last update I should write this:
```typescript
@Module({
  imports: [
    TypeOrmModule.forRoot({
      /* Connection options goes here */,
      entities: [/* Entities goes here */],
    }),
    TypeOrmModule.forFeature([/* Entities goes here */]),
  ]
})
```
Why? I've already pass my entities inside options. And now I importing the same module twice.

**Comment by kamilmysliwiec** [comment]
Hi @FriOne,
Take a look here: https://docs.nestjs.com/techniques/sql

**Comment by FriOne** [comment]
Hi, @kamilmysliwiec, well, if I have one root module, I should import the orm module twice :(
Actually I don't want use config file because I prefer to control it from code.

**Comment by fwoelffel** [comment]
Is your code sample even working? I'm trying to do something very similar (btw, I'm okay with the TypeORM module design; perhaps should I post this in a new issue).

```js
import {Module} from '@nestjs/common';
import {TypeOrmModule} from "@nestjs/typeorm";

import {AnimalsService} from './services/animals/animals.service';
import {AnimalsController} from './controllers/animals/animals.controller';
import {Animal} from "./entities/animal.entity";

@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'postgres',
      host: process.env.hasOwnProperty('POSTGRES_HOST') ? process.env.POSTGRES_HOST : '127.0.0.1',
      port: process.env.hasOwnProperty('POSTGRES_PORT') ? Number(process.env.POSTGRES_PORT) : 5432,
      username: process.env.hasOwnProperty('POSTGRES_USERNAME') ? process.env.POSTGRES_USERNAME : 'basicuser',
      password: process.env.hasOwnProperty('POSTGRES_PASSWORD') ? process.env.POSTGRES_PASSWORD : 'ultrastrongpassword',
      database: process.env.hasOwnProperty('POSTGRES_DB') ? process.env.POSTGRES_DB : 'ris',
      entities: [ Animal ],
      synchronize: true
    }),
    TypeOrmModule.forFeature([ Animal ])
  ],
  components: [
    AnimalsService
  ],
  controllers: [
    AnimalsController
  ]
})
export class AnimalsModule {}
```
When I start my app, I get the following error:
```
[Nest] 26187   - 2018-1-17 10:06:49   [NestFactory] Starting Nest application...
[Nest] 26187   - 2018-1-17 10:06:49   [InstanceLoader] ApplicationModule dependencies initialized +9ms
[Nest] 26187   - 2018-1-17 10:06:50   [InstanceLoader] ProjectsModule dependencies initialized +173ms
[Nest] 26187   - 2018-1-17 10:06:50   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 26187   - 2018-1-17 10:06:50   [InstanceLoader] TypeOrmCoreModule dependencies initialized +2ms
[Nest] 26187   - 2018-1-17 10:06:50   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 26187   - 2018-1-17 10:06:50   [InstanceLoader] ProtocolsModule dependencies initialized +3ms
[Nest] 26187   - 2018-1-17 10:06:50   [ExceptionHandler] No repository for "Animal" was found. Looks like this entity is not registered in current "default" connection?
```

It looks like the `TypeOrmModule.forFeature` call is done too soon. Is there any way to make sure that the Connection and Repositories are initialized before the `forFeature` call?

**Comment by kamilmysliwiec** [comment]
`It looks like the TypeOrmModule.forFeature call is done too soon`
That's not possible. To create repositories typeorm need connection instance that is provided by `forRoot()`. If `forFeature` is called before `forRoot` you would receive an exception that `connection` is not available yet.

**Comment by fwoelffel** [comment]
I found my issue ;)
It is because, in another module, I also use `TypeOrmModule.forRoot` to get a connection to another database. I've looked through the code and I understand that there is currently no way to handle multiple connections with this TypeORM module. Is it planned? (would you like me to create a new issue for this?)

**Comment by kamilmysliwiec** [comment]
@fwoelffel saw your pull request, will verify soon :)

**Comment by obedm503** [comment]
it's still wierd to pass entities twice, will it be posible to omit the `TypeOrmModule.forFeature` call?

**Comment by fwoelffel** [comment]
The `forRoot` provides the `Connection` and the `forFeature` provides the `Repositories`. There's nothing weird in that ;)

**Comment by obedm503** [comment]
But I would guess that if I'm already passing the entities to `forRoot` that that also registers the entities and provides the repositories

**Comment by FriOne** [comment]
@obedm503 yeah, I have the same thought about it. It will be great if `forRoot` method creates repositories for entities if they was provided as classes array. We can have both methods implemented.
Also `forFeature` name doesn't explain what the function actually do. It is better to call it `provideRepositories` or smth like that.

**Comment by fwoelffel** [comment]
What about people who:
- uses `forRoot` in a `DatabaseModule` which exports the instanciated connection
- uses `forFeature([ User ])` in a `UserModule` which imports the `DatabaseModule`
- uses `forFeature([ Car ])` in a `CarModule` which imports the `DatabaseModule`
- doesn't want the `Repository<User>` available in the `CarModule`
- doesn't want the `Repository<Car>` available in the `UserModule`

I don't think that what you're asking for would allow that design.

**Comment by obedm503** [comment]
I'm not saying we should get rid of `forFeature`, I'm just saying that if the entities are already registered in the root module using `forRoot`, then `forFeature` is unnecessary in the child modules. on the other hand, if it's registered in a child module but not in the root module, then it would only be available for the child module, and not the entire app

**Comment by FriOne** [comment]
@fwoelffel In case which you described, entities will be passed to options as regexp string, not by importing entities classes. I mean why should we import them as classes into `forRoot` in this case? So no repositories will not be provided without `forFeature` calls.

**Comment by Snejjot** [comment]
Can GraphQL introduction somehow brake this feature? 
For some reasons - not working, but entities are definitely visible as server restart after tables drop - recreate tables on the basis of entities, but once I use .forFeature in the module - it stops to see the Entity.
