### ISSUE TITLE
How to get a dependency inject database configuration

### ISSUE THREAD

**Issue by tonyxiao** [nestjs/typeorm#43]
I'm following this pattern of creating a `ConfigService` that encapsulates all the configuration in the application. This works really well. However when working with `TypeORMModule`, it seems that I need to provide the database credentials at module load time. 

```

@Module({
  imports: [TypeOrmModule.forRoot(getDbConfig())], // this line
  providers: [...repoProviders],
  exports: [...repoProviders],
})
export class DBModule {}
```

I would like to provide the `getDbConfig()` values via dependency injecting `ConfigService`. Can that be done?

**Comment by kamilmysliwiec** [comment]
There is a long discussion about this issue here: https://github.com/nestjs/nest/issues/530
I'll share a solution very soon.

**Comment by kamilmysliwiec** [comment]
Just answered
