### ISSUE TITLE
TypeError: Cannot set property EntityManager of #<Object> which has only a getter

### ISSUE THREAD

**Issue by AntoninSorrento** [nestjs/typeorm#468]
## Error
![image](https://user-images.githubusercontent.com/26902024/81761011-5ca15300-94fb-11ea-8c7d-925b0142178c.png)

## Set
![image](https://user-images.githubusercontent.com/26902024/81761037-6f1b8c80-94fb-11ea-988c-2081cd5e9e45.png)
![image](https://user-images.githubusercontent.com/26902024/81761048-7773c780-94fb-11ea-876c-1d110aa6c39c.png)
![image](https://user-images.githubusercontent.com/26902024/81761072-8b1f2e00-94fb-11ea-916b-06afb10c26ad.png)

## Verison
![image](https://user-images.githubusercontent.com/26902024/81761215-f2d57900-94fb-11ea-9e99-a1f283f20fb4.png)

**Comment by kamilmysliwiec** [comment]
Please, report this here https://github.com/typeorm/typeorm

**Comment by kamilmysliwiec** [comment]
Oh actually, see this issue https://github.com/typeorm/typeorm/issues/6054

**Comment by AntoninSorrento** [comment]
thank you !  @kamilmysliwiec
