### ISSUE TITLE
Multi tenancy with Nest and TypeOrm and Postgres?

### ISSUE THREAD

**Issue by murbanowicz** [nestjs/typeorm#58]
Hello,

It is really question not an issue but it may be good place to ask.
I am working on multi tenant application using nest. So far I have started by creating common base service and controllers which filter, check and assign tenant_id based on current context.
However having postgres schema per tenant would be better I think but i don't known how to implement it with nest and typeorm. 
Any suggestions?

**Comment by kejhme** [comment]
I have the similiar problem, please any solution?

**Comment by kejhme** [comment]
I'm working with mongoose, and I want to use multi tenant, but I don´t find how do it

**Comment by kamilmysliwiec** [comment]
Once 6.0.0 will be published, you'll be able to switch to the per-request instances lifetime + inject `@Inject(REQUEST)` will be possible as well. Then, it should be fairly easy to choose a connection based on the request properties.

**Comment by kesali** [comment]
Is there any example of implementing multi tenancy?

**Comment by felixhayashi** [comment]
@kesali 

Here are a few inspirations:

* https://stackoverflow.com/questions/57459643/typeorm-dynamically-set-database-schema-for-entitymanager-or-repositories-at-ru/60128226#60128226
* https://stackoverflow.com/questions/56583231/nestjs-request-scoped-multitenancy-for-multiple-databases
* https://github.com/typeorm/typeorm/issues/3811
* https://stackoverflow.com/questions/51385738/nestjs-database-connection-typeorm-by-request-subdomain
* https://stackoverflow.com/questions/56085705/how-can-i-setup-multitenant-in-nestjs

**Comment by fabiofdsantos** [comment]
@kesali https://github.com/juicycleff/ultimate-backend

**Comment by kesali** [comment]
@fabiofdsantos @felixhayashi Thanks for the responses.

**Comment by edge721** [comment]
https://docs.nestjs.com/fundamentals/custom-providers#factory-providers-usefactory

**Comment by adrienbarreau** [comment]
@kesali here is an example => https://tech.canyonlegal.com/multitenancy-with-nestjs-typeorm-postgres

**Comment by cassioseffrin** [comment]
> @kesali here is an example => https://tech.canyonlegal.com/multitenancy-with-nestjs-typeorm-postgres

Do you have a github repository with this awesome POST?
