### ISSUE TITLE
Query Builder is not supported by MongoDB

### ISSUE THREAD

**Issue by one-coder6** [nestjs/typeorm#627]
![image](https://user-images.githubusercontent.com/20533100/92376872-cfcb7680-f135-11ea-9c9e-48b5cc2989c5.png)

![image](https://user-images.githubusercontent.com/20533100/92376910-e376dd00-f135-11ea-9a7f-0c0980da1313.png)

What should I do...

**Comment by kamilmysliwiec** [comment]
Please, ask this question here https://github.com/typeorm/typeorm
