### ISSUE TITLE
Provide an example of usage custom repository in another one

### ISSUE THREAD

**Issue by vladmelnikov** [nestjs/typeorm#63]
## Current behavior
i am trying to inject repository in another like 
![image](https://user-images.githubusercontent.com/13378944/52479956-5ebf8800-2bbb-11e9-8518-ef048e941e03.png)

but when i am trying to use method from injected repository i am getting error:
this.issueRepository.getProjects is not a function, but it is a function and i can call it inside service

## Expected behavior 

![image](https://user-images.githubusercontent.com/13378944/52480228-1fde0200-2bbc-11e9-835c-d78688115771.png)

## Environment

<pre><code>
Nest version: 5.4.0
Nest/typeorm version: 5.2.2
 
For Tooling issues:
- Node version: 9.9.0
- Platform:   Windows

**Comment by Dominic-Preap** [comment]
@vladmelnikov I also think something like this too. But we can use `getCustomRepository` instead.

```ts
@EntityRepository(Photo)
export class PhotoRepository extends Repository<Photo> {
  findMe(id: number) {
    return this.findOne({ id });
  }
}

@EntityRepository(User)
export class UserRepository extends Repository<User> {
  async findByMyId(id: number) {
    const photoRepository = this.manager.getCustomRepository(PhotoRepository);
    const a = await photoRepository.findMe(id);
    const b = await this.findOne({ id });
    return { a, b };
  }
}

```

**Comment by vladmelnikov** [comment]
@Dominic-Preap thanks a lot. Exactly what I was looking for.

**Comment by stankela96** [comment]
@Dominic-Preap Man, i've been looking for this from early morning. Thank you so much 👊
