### ISSUE TITLE
how can I use EntityManager to complete this sql

### ISSUE THREAD

**Issue by Erchoc** [nestjs/typeorm#633]
> SELECT * FROM `user` WHERE `name` = 'yangxj' AND `start_time` BETWEEN 'a1' TO 'b1' OR `end_time` BETWEEN 'a2' TO 'b2';

plese help me，I think typeorm entityManager could not do this.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
