### ISSUE TITLE
Nestjs can't resolve dependencies of my provider with named "providerRepository" 

### ISSUE THREAD

**Issue by maximosdrr** [nestjs/typeorm#639]
## Bug Report
 Nest can't resolve dependencies of the  UserRepository (?). Please 
make sure that the argument UserRepository at index [0] is available in the UserModule context.

Potential solutions:
- If UserRepository is a provider, is it part of the current UserModule?
- If UserRepository is exported from a separate @Module, is that module imported within UserModule?
  @Module({
    imports: [ /* the Module containing  UserRepository */ ]
  })
## Current behavior
I was making an api for a cafeteria that used a repository, and then I made a class of repository for the users that was called "UserRepository" in it I injected Typeorm so that for some reason Nestjs couldn't solve the dependency of the typeorm, I tried everything until we despair I decided to change the class name which to my surprise worked, so I changed from "UserRepository" to "UserRepo" which ended up solving my problem

## Input Code
`import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { DeleteResult, InsertResult, Repository } from 'typeorm';
import { User } from '../../entities/user.entity';
import { IUserRepository } from './interface';

@Injectable()
export class **UserRepo**(UserRepository not works here) implements IUserRepository {
  constructor(@InjectRepository(User) private db: Repository<User>) {}

  async findUserByPayload(user: User): Promise<User> {
    return await this.db.findOne({
      where: {
        name: user.name,
      },
    });
  }

  async insert(user: User): Promise<InsertResult> {
    return await this.db.insert(user);
  }
  async findAll(): Promise<User[]> {
    return await this.db.find();
  }
  findOne(user: string): Promise<User> {
    return this.db.findOne(user);
  }
  async findByName(user: string): Promise<User[]> {
    return await this.db.find({
      where: { name: user },
    });
  }

  async update(user: User): Promise<User> {
    return await this.db.save(user);
  }
  async delete(user: string): Promise<DeleteResult> {
    return await this.db.delete(user);
  }
}
`

## Possible Solution
Change class name?

## Environment
Development

<pre><code>
Nest version: 7.4.1
 
For Tooling issues:
- Node version: v14.8.0
- Platform:  Windows

Others:
IDE: Vscode
Package Manager: NPM
Database: Mysql
Orm: Typeorm

**Comment by Sikora00** [comment]
I'm facing the same issue. Probably because @InjectRepository(User) under the hood creates "UserRepository" (Entity name + "Repository") injection token so the same as the class you are trying to create. Is it possible that we have a conflict of names here?

**Comment by kamilmysliwiec** [comment]
This is fixed in this PR https://github.com/nestjs/nest/pull/6349
