### ISSUE TITLE
how to fine SQL error in project?

### ISSUE THREAD

**Issue by webafra** [nestjs/typeorm#738]
hi.
please help me to fine error in my project:

Where did this error occur?
In which file?
In which line?

![image](https://user-images.githubusercontent.com/8689072/101651759-a848ba80-3a52-11eb-902d-bf55dbe69331.png)

Node js: 14.12.0
Nest Version: 7.4.1
nest/typeOrm version: 7.1.5
Databse: mariaDb Version 10.5.7

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
