### ISSUE TITLE
Dynamically loading config from another service for use in TypeORM config

### ISSUE THREAD

**Issue by Prashvith** [nestjs/typeorm#880]
https://github.com/nestjs/typeorm/issues/29. 
I have a requirement similar to the above issue. But in my case I need to fetch it from another service through GRPC. How can I achieve this?
@BrunnerLivio

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
