### ISSUE TITLE
RepositoryNotFoundError

### ISSUE THREAD

**Issue by Gecko222** [nestjs/typeorm#9]
I have one entity(Player) and path in config is 100% good, because typeorm is creating table in db AND when im using `this.connection.getRepository("Player"`) it finds it too(no error), but when im trying to import it using `TypeOrmModule.forFeature([Player])` i got this error.

@edit
i just find out that if in `this.connection.getRepository` im using `Player` class, not string it throws error too.

Code: https://github.com/Gecko222/game/tree/backend-refactor/src_server

PS. Stacktrace is showing wierd path:
```
Error
    at new RepositoryNotFoundError (E:\repos\game\src\error\RepositoryNotFoundError.ts:12:22)
    at EntityManager.getRepository (E:\repos\game\src\entity-manager\EntityManager.ts:769:19)
    at Connection.getRepository (E:\repos\game\src\connection\Connection.ts:306:29)
    at getRepository (E:\repos\game\node_modules\@nestjs\typeorm\typeorm.providers.js:8:22)
    at Object.useFactory [as metatype] (E:\repos\game\node_modules\@nestjs\typeorm\typeorm.providers.js:11:37)
    at Injector.<anonymous> (E:\repos\game\node_modules\@nestjs\core\injector\injector.js:84:59)
```

i dont have folder src.

**Comment by kamilmysliwiec** [comment]
Hi @Gecko222,
Honestly, I don't think that this issue is caused by nest module. It looks like `typeorm` can't find your entities. Btw, why you are not using `@nestjs/typeorm` package?

**Comment by Gecko222** [comment]
Propably its not nestjs/typeorm issue, but i find out it after making this issue and was hoping you can help.
Im not using @nestjs/typeorm becouse of this:
 `connection.getRepository(entity)` => `connection.getRepository(entity.name)`
as i said typeorm can find entity only by name of class, not sure why.

anyway thanks for anwer. i will investigate typeorm and this issue later, I do not feel like doing it right now.

**Comment by kamilmysliwiec** [comment]
Ah gotcha. Let's try to create an issue here https://github.com/typeorm/typeorm. I never had a similar issue 🙁

**Comment by Gecko222** [comment]
Ok, thank you :)

**Comment by unlight** [comment]
And still, it's more related to `typeorm`
All entities must be registered on initial connection.

**Comment by Gecko222** [comment]
Well i found out that (at least at my issue) it was related to how node imports modules and in my configuration it was importing entity as diffrent symbols(i understood it that way, Player !== Player). I end up with importing every entitie in module where i use TypeOrmModule.forRoot(), but im using same stack(nest+typeorm) in diffrent project and im using .json config and everything is fine, so im still not sure whats wrong.

**Comment by rizvanhaider** [comment]
I was facing the same issue but what fixed for me is I was missing the decorator `@Entity()` in my entity file.

**Comment by Overfacto** [comment]
In my case I could resolve this issue with typeorm entities setting correction.

And I found nestjs loads typeorm entities or subscribers as 'Object' while pure typeorm fetched entities or subscribers with that types 

and they can be found with instanceof syntax.

I think it is because of nestjs try to load entities from build result(dist).

try console logging __dirname, at least on my issue, I can catch what is the wrong

**Comment by PiotrSzlagura** [comment]
@rizvanhaider Thank you! I missed it too, and couldn't find reason for which my entities wouldn't work.

**Comment by zaghir** [comment]
Clean all files from /dist folder and start your application 
This is the config for posgresql/nestjs/typeorm which i use 
const connexionAtsDb: TypeOrmModuleOptions = {
  type: 'postgres',
  host: 'localhost',
  port: 5432,
  username: 'postgres',
  password: 'admin',
  database: 'pass',  
  schema: 'warehouse',
  entities: [__dirname + '/../**/*.entity.{js,ts}'],
  synchronize: true, 
};
i hope to fix your problem

**Comment by Juriy** [comment]
For me an issue was that the original entity discovery pattern was (notice, "ts" only at the end): `__dirname + '/../**/*.entity.ts'` 
 
Changing the pattern to: `__dirname + '/../**/*.entity.{js,ts}'` did the trick. 

To make matters worse, when I was launching the project from WebStorm with command like this:
```
node -r ts-node/register -r tsconfig-paths/register src/main.ts
```

It was working well even with the original patter. It was only when I tried to run project with `npm start`

That I noticed an issue.
