### ISSUE TITLE
How to log error TypeOrmModule ? 

### ISSUE THREAD

**Issue by zellkon** [nestjs/typeorm#929]
I'm getting an error MySQL server version for the right syntax to use near ') NOT NULL' at line 1 when I start a project

![image](https://user-images.githubusercontent.com/20116654/124382899-ed388500-dcf3-11eb-9ed6-97cb7d3d03af.png)

I don't know how to fix it without a specific error? 
Please help me! Thank

**Comment by Tony133** [comment]
Hi @zellkon, 

The error it gives you is referring to an error in the SQL syntax, maybe there is a comma or a bracket too many and it cannot connect to the database.

For this type of question I recommend using the [Discord](https://discord.com/invite/G7Qnnhy) channel.

**Comment by jmcdo29** [comment]
[TypeORM has this documented](https://typeorm.io/#/logging). If you have other problems, [raise an issue with them](https://github.com/typeorm/typeorm/issues/new/choose) or use our [Discord}(https://discord.gg/nestjs) for Support.
